### ISSUE TITLE
Checksum has changed for IIS-ARR package 

### ISSUE THREAD

**Issue by andmos** [bcc/choco-packages#4]
Not sure if you want an Issue here as well, so I post it anyways. 
Seems like the checksum has changed again: 
```
Verifying with package checksum to determine if it needs to be redownloaded.\r\nError - hashes do not match. Actual value was 'EFF9901CE6C20F94055488E65D3D2748B4E2BE8E'.
```

**Comment by bcc** [comment]
Thanks. This silent checksum change has broken MS own WebPI tool too, so I'm holding off on the update until it's clear that it's expected.

**Comment by bcc** [comment]
MS have reverted the MSI to the old version as there were other issues with the new version they released. I'm told they're looking to improve how this process works, so hopefully this version mismatch can be prevented in future.
