### ISSUE TITLE
Checksum has changed for IIS-ARR

### ISSUE THREAD

**Issue by ghost** [bcc/choco-packages#7]
As can be seen in my gist: https://gist.github.com/ryanbrown-iress/8877a27878286f38f541388bc5e3ee9b, the checksum for iis-arr have been updated in Microsoft's CDN.

I have created a PR to rectify this, feel free to verify or let me know if any other changes are needed: https://github.com/bcc/choco-packages/pull/6

**Comment by bcc** [comment]
Thanks, sorry for the delay looking at this. The PR looks good, I've confirmed the checksums, and I've pushed a new package which is currently waiting on moderation.
